### ISSUE TITLE
Nice plugin idea

### ISSUE THREAD

**Issue by acosonic** [brunofonseca/redmine_process_dashboard#1]
Can you provide more details on how to install and use this plugin?

**Comment by brunofonseca** [comment]
Hi @acosonic ! Thanks for following the plugin development.

Basically, the main goals of this plugin are described below:

Objective: To give visibility in the tasks of processes / projects that are important in their respective stage. Steps are defined as being non-pane lines.

I assume that each stage is a process, so macro-defined milestones (columns) in which group different situations of tasks.
In each project, you set up tasks with your defined workflow and permissions.

These processes determine all steps without development of a demand, where tasks are created in all actions.

Through this dashboard I want to get indicators of how is an evolution in each process from macro way to its detail, so that everyone can take punctual actions and have visibility these tasks.

At this point I am not measuring whether there is bottleneck with how tasks versus resources are available in each process, giving an indicator of resource allocation. I believe that it evolves to this information, since it is also analyzing also the volume of tasks with the resources allocated in each stage of the process.

**Comment by brunofonseca** [comment]
@acosonic , The plugin development process started last Monday, so there are no installation-specific details that should follow the standard plugin installation process in redmine 3.x.
